//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Etudiant__WPF.GestionEtudiant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int ID_Etudiant { get; set; }
        public string CNE { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string adresse { get; set; }
        public string tele { get; set; }
        public Nullable<int> age { get; set; }
        public string photo { get; set; }
        public Nullable<int> ID_Filiere { get; set; }
    
        public virtual Filiere Filiere { get; set; }
    }
}
